//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tCompany
    {
        public int ID_Company { get; set; }
        public string Company_name { get; set; }
        public System.DateTime dateofcreation { get; set; }
        public int ID_type { get; set; }
        public int ID_worker { get; set; }
    }
}
