//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BuySell.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tWorker
    {
        public int ID_worker { get; set; }
        public string sFIO { get; set; }
        public System.DateTime bithday { get; set; }
        public string passport { get; set; }
        public string passportinfo { get; set; }
        public string address { get; set; }
        public string phone { get; set; }
        public string base_worker { get; set; }
        public Nullable<int> experience { get; set; }
        public string special { get; set; }
        public Nullable<double> price { get; set; }
    }
}
